services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  ollama:
    image: ollama/ollama:0.5.5
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  data_loader:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/pgvector
      - OLLAMA_HOST=ollama
    depends_on:
      - db
      - ollama
    command: python csv_data.py
    volumes:
      # Map the /app/data directory inside the container to the ./data directory on the host
      - ./data:/app/data
  flask_app:
    build:
      context: .
      dockerfile: server/Dockerfile # Dockerfile specifically for Flask
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/pgvector
    depends_on:
      - db
    ports:
      - "5000:5000" # Expose Flask server on port 5000
volumes:
  pgdata:
  ollama_data:
